/* Copyright (c) 2026 lamosquita. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_RENDERER_FLYWEB_FLYWEB_POLYFILLS_RENDER_FRAME_OBSERVER_H_
#define BRAVE_RENDERER_FLYWEB_FLYWEB_POLYFILLS_RENDER_FRAME_OBSERVER_H_

#include "base/feature_list.h"
#include "content/public/renderer/render_frame_observer.h"

namespace flyweb {

// Injects polyfills (core-js, generated by softmac FlyWeb/polyfills) for
// JavaScript features that the web now takes for granted and Chromium 116
// lacks. Disable with --disable-features=FlyWebPolyfills to tell a missing
// feature from any other site breakage.
BASE_DECLARE_FEATURE(kFlyWebPolyfills);

// Runs the polyfills in the main world of every http(s) document before any
// page script: DidClearWindowObject fires when the new window object is
// created. The script is executed by the renderer itself, so the page's CSP
// does not apply. Workers are not covered.
class FlyWebPolyfillsRenderFrameObserver : public content::RenderFrameObserver {
 public:
  explicit FlyWebPolyfillsRenderFrameObserver(
      content::RenderFrame* render_frame);
  FlyWebPolyfillsRenderFrameObserver(
      const FlyWebPolyfillsRenderFrameObserver&) = delete;
  FlyWebPolyfillsRenderFrameObserver& operator=(
      const FlyWebPolyfillsRenderFrameObserver&) = delete;
  ~FlyWebPolyfillsRenderFrameObserver() override;

  // content::RenderFrameObserver:
  void DidClearWindowObject() override;
  void OnDestruct() override;
};

}  // namespace flyweb

#endif  // BRAVE_RENDERER_FLYWEB_FLYWEB_POLYFILLS_RENDER_FRAME_OBSERVER_H_
